### ISSUE TITLE
Is it possible to use a comment to indicate which column is the timestamp?

### ISSUE THREAD

**Issue by panqingfeng** [TongchengOpenSource/ckibana#12]
example:
CREATE TABLE ops.ops_nginx_local
(
`request_method` LowCardinality(String),
`request_uri` String,
`status` Int64,
`request_time` Float64,
`request_length` Int64,
`http_referer` String,
`http_user_agent` String,
`http_host` String,
`request_id` String,
`remote_addr` String,
`bytes_sent` Int64,
`body_bytes_sent` Int64,
`logtime` UInt64  COMMENT 'TIMESTAMP',
`ck_assembly_extension` String,
INDEX timestamp_index `@timestamp` TYPE minmax GRANULARITY 8192
)
ENGINE = MergeTree
PARTITION BY (toYYYYMMDD(toDateTime(`@timestamp` / 1000, 'Asia/Shanghai')), toHour(toDateTime(`@timestamp` / 1000, 'Asia/Shanghai')))
ORDER BY (`http_host`, intHash64(`@timestamp`))
SAMPLE BY intHash64(`@timestamp`)
SETTINGS in_memory_parts_enable_wal = 0, index_granularity = 8192

In this case, we do not have a required column named '@timestamp’， ckibana knows 'logtimes' is the '@timestamp' base on comment( which include 'TIMESTAMP' substring)

**Comment by linger000** [comment]
https://tongchengopensource.github.io/ckibana-docs/en/troubleshooting#3when-creating-an-index-pattern-the-time-field-cannot-be-selected
