### ISSUE TITLE
添加白名单索引后 还是无法发现对应的clickhouse 的表

### ISSUE THREAD

**Issue by jiaozi07** [TongchengOpenSource/ckibana#34]
## CKibana info
**CKibana version**:  v1.0.2
**ClickHouse version**: i.e. `23.4.1.1943`
**Operating system version**: e.g.  CentOS 7 
**k8s version**: v1.26.4
elasticsearch  kibana 8.8 

![image](https://github.com/TongchengOpenSource/ckibana/assets/13267004/14e609e1-58a3-47e4-9fdd-dfa0cb8ad583)

**Comment by qzhello** [comment]
麻烦贴一下proxy-settings里的配置吧

**Comment by jiaozi07** [comment]
2024-05-08 17:57:50.578  INFO - [nio-8080-exec-4] [com.ly.ckibana.handlers.BaseHandler     ] :[LxXEYLJDNQQdLbQ] update settings:[proxy-settings], body:defaultShard: 2
proxy:
  blackIndexList: []
  ck:
    defaultCkDatabase: test
    pass: password
    url: 10.0.0.1:9000
    user: admin
  enableMonitoring: false
  es:
    headers:
      Authorization: Basic xxxxxxxxx=
      mock: mock
      yourHeaderKey: yourHeaderValue
    host: https://10.0.0.2:9200
  maxTimeRange: 0
  round: 0
  roundAbleMinPeriod: 120000
  whiteIndexList:
  - testlog
query:
  maxResultRow: 30000
  sampleCountMaxThreshold: 0
  sampleIndexPatterns:
  - testlog
  useCache: true
threadPool:
  commonProperty:
    coreSize: 4
    queueSize: 10000
  msearchProperty:
    coreSize: 4
    queueSize: 10000
, response:[{"took":1,"errors":false,"items":[{"index":{"_index":"proxy-settings","_id":"kibana","_version":17,"result":"updated","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":16,"_primary_term":1,"status":200}}]}]

**Comment by jiaozi07** [comment]
```
2024-05-08 17:57:50.574  WARN - [nio-8080-exec-4] [c.l.c.c.web.adpter.BaseHandlerAdapter   ] :[LxXEYLJDNQQdLbQ] [POST] uri: /config/updateSampleIndexList
2024-05-08 17:57:50.578  INFO - [nio-8080-exec-4] [com.ly.ckibana.handlers.BaseHandler     ] :[LxXEYLJDNQQdLbQ] update settings:[proxy-settings], body:defaultShard: 2
proxy:
  blackIndexList: []
  ck:
    defaultCkDatabase: test
    pass: pass
    url: 10.0.0.1:9000
    user: admin
  enableMonitoring: false
  es:
    headers:
      Authorization: Basic xxxxxxxxxx=
      mock: mock
      yourHeaderKey: yourHeaderValue
    host: https://10.0.0.2:9200
  maxTimeRange: 0
  round: 0
  roundAbleMinPeriod: 120000
  whiteIndexList:
  - testlog
query:
  maxResultRow: 30000
  sampleCountMaxThreshold: 0
  sampleIndexPatterns:
  - testlog
  useCache: true
threadPool:
  commonProperty:
    coreSize: 4
    queueSize: 10000
  msearchProperty:
    coreSize: 4
    queueSize: 10000
, response:[{"took":1,"errors":false,"items":[{"index":{"_index":"proxy-settings","_id":"kibana","_version":17,"result":"updated","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":16,"_primary_term":1,"status":200}}]}]



```

**Comment by linger000** [comment]
仅在库有目标表且白名单配置后，才能展示到indexpattern列表
项目日志中有[query]sql=SELECT name FROM system.tables WHERE database = '你的库名'的相关日志。
步骤1）手动执行sql。确认是否真实存在你要配置的目标表
步骤2）若1不存在，则创建表。若1存在，检测是否和白名单配置的名称一致

**Comment by jiaozi07** [comment]
1. 数据库以及目标表都是存在的  
2. 跟白名单配置名称一致

**Comment by jiaozi07** [comment]
```
clickhouse-server-548cc945c4-qjccr :) SELECT name FROM system.tables WHERE database = 'test'

SELECT name
FROM system.tables
WHERE database = 'test'

Query id: bc405a89-6772-461e-afc4-5f602b65c53e

┌─name────┐
│ testlog │
└─────────┘

1 row in set. Elapsed: 0.001 sec. 
```

**Comment by qzhello** [comment]
你好，增加了个check接口，用于自测下，该接口打印了db信息、白名单配置，查询sql，是否命中等。
接口：`curl --location 'http://localhost:8080/check/您的表名'`

相关：https://github.com/TongchengOpenSource/ckibana/pull/35

**Comment by jiaozi07** [comment]
使用8123端口可以了
