### ISSUE TITLE
n9e创建索引模式时无法搜索到对应的表结构

### ISSUE THREAD

**Issue by jiaozi07** [TongchengOpenSource/ckibana#40]
![image](https://github.com/TongchengOpenSource/ckibana/assets/13267004/2a545d19-b43c-4504-a44a-041b9db9374e)

手动填写后可以进行查询
![image](https://github.com/TongchengOpenSource/ckibana/assets/13267004/442d47f0-edb3-4e9f-9353-d1435d224fa2)

![image](https://github.com/TongchengOpenSource/ckibana/assets/13267004/a98492b3-9637-43db-aab3-683020398a61)

**Comment by famosss** [comment]
ok,我们适配一下这个api

**Comment by jiaozi07** [comment]
无法获取到字段信息
![image](https://github.com/TongchengOpenSource/ckibana/assets/13267004/37ef91eb-1b36-4007-8b5c-4e97aa556364)

**Comment by caojiaqiang** [comment]
![1](https://github.com/TongchengOpenSource/ckibana/assets/11900397/867876a8-28b2-4b51-85ff-dd240671d5da)
![1](https://github.com/TongchengOpenSource/ckibana/assets/11900397/867876a8-28b2-4b51-85ff-dd240671d5da)
无法获取到字段信息不属于ckibana的问题，应该是n9e的问题，试了使用原生的ES，创建index pattern，也会无法获取到字段信息（n9e 6.5版本）
![2](https://github.com/TongchengOpenSource/ckibana/assets/11900397/7b669f03-51bc-49ac-87e4-13a82d045c5f)
![2](https://github.com/TongchengOpenSource/ckibana/assets/11900397/7b669f03-51bc-49ac-87e4-13a82d045c5f)

**Comment by famosss** [comment]
> 无法获取到字段信息不属于ckibana的问题，应该是n9e的问题，试了使用原生的ES，创建index pattern，也会无法获取到字段信息（n9e 6.5版本） ![3](https://private-user-images.githubusercontent.com/11900397/343157823-9fc490fa-84fb-484f-8cda-6820f97ed414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDg5MjksIm5iZiI6MTcxOTQ0ODYyOSwicGF0aCI6Ii8xMTkwMDM5Ny8zNDMxNTc4MjMtOWZjNDkwZmEtODRmYi00ODRmLThjZGEtNjgyMGY5N2VkNDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAwMzcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNjA5YzBhZWQ4MzFiNjhjYjM4ODE1OWQ3ZTFiZTUzZGQ5NWZkNjQ4YWRlYWI0ZDYxZGY4ZjY5MzFkMzQ0MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OnPPU0hLvnbk-zHwfDHxpfk03Brnbpn9TdN_Kg6zAg4)

换个es版本试试

**Comment by caojiaqiang** [comment]
你好，使用n9e创建索引模式时无法搜索到ck对应表的问题已修复 #48

**Comment by caojiaqiang** [comment]
但是不建议用n9e创建ck表对应的index pattern，因为n9e创建的index pattern只会存在n9e自身的表中，不会跟ES交互，如果只是在n9e中创建ck表对应的index pattern，ES中不会有该index pattern的元数据信息，查询会报如下信息
![1](https://github.com/TongchengOpenSource/ckibana/assets/11900397/bd50e581-520a-4bab-a9c8-a2f09fd2ecc3)
