### ISSUE TITLE
_source 字段重复展示

### ISSUE THREAD

**Issue by VinnyWan** [TongchengOpenSource/ckibana#53]
![QQ_1721383905195](https://github.com/user-attachments/assets/9baab115-83fd-4846-886e-3dffbcf153b6)
在使用最新版的 ckibana 时， 会出现 _source出现重复展示的情况， 想要做成直接_source 展示，可以支持下吗？

**Comment by linger000** [comment]
如图上所示，应该是您自定义clickhouse字段中包含_source字段。建议删除此字段
