### ISSUE TITLE
kibana dashboard 展示问题

### ISSUE THREAD

**Issue by Warmdust** [TongchengOpenSource/ckibana#58]
kibana dashboard 展示排序有问题，但是数据是准确的。

实际体验下来，数据比较大的时候，才会出现排序问题，小数据的时候不会出现排序问题

![image](https://github.com/user-attachments/assets/a1e14ee9-a440-4416-a462-73ff25a8d629)

![image](https://github.com/user-attachments/assets/e2eb3d4d-7e8a-493b-bd13-5d458ddbaa91)

**Comment by linger000** [comment]
按上面配置条件，应该x-axis 是ip。x和y-axis互换是如何配置，辛苦提供下截图。

**Comment by linger000** [comment]
模拟上面sum数据量，是没有问题的。这个视图配置是直接使用ck group by order by 语法，建议f12看下对应视图的sql,ck上直接执行看下结果。用于识别是否字段类型或值引发的问题。
若还有疑问，提供下一个正常和一个非正常视图的对应sql和表结构

**Comment by linger000** [comment]
已修复。
https://github.com/TongchengOpenSource/ckibana/pull/66

**Comment by linger000** [comment]
已修复。
https://github.com/TongchengOpenSource/ckibana/pull/66
