### ISSUE TITLE
使用KQL语法查询报错

### ISSUE THREAD

**Issue by zhxgigi** [TongchengOpenSource/ckibana#60]
## Describe the bug

使用KQL语法查询报错，使用Lucene语法没问题。

## CKibana info

Please include the following information about your environment:

**CKibana version**: 1.0.4
**ClickHouse version**: i.e. na
**Kibana**: 7.17.4, Elastcisearch: 7.17.4

## Steps to reproduce

Kibana开启KQL查询功能
<img width="1303" alt="image" src="https://github.com/user-attachments/assets/0555e618-f436-4092-a997-887872cbe23a">

<img width="474" alt="image" src="https://github.com/user-attachments/assets/57d70e07-8b19-4e7c-969d-bc88c2edbed8">

请求：
`{
  "batch": [
    {
      "request": {
        "params": {
          "index": "xxxxxxxxx",
          "body": {
            "sort": [
              {
                "ts": {
                  "order": "desc",
                  "unmapped_type": "boolean"
                }
              }
            ],
            "fields": [
              {
                "field": "*",
                "include_unmapped": "true"
              },
              {
                "field": "collect_ts",
                "format": "strict_date_optional_time"
              },
              {
                "field": "ts",
                "format": "strict_date_optional_time"
              },
              {
                "field": "ts_min",
                "format": "strict_date_optional_time"
              }
            ],
            "size": 800,
            "version": true,
            "script_fields": {},
            "stored_fields": [
              "*"
            ],
            "runtime_mappings": {},
            "_source": false,
            "query": {
              "bool": {
                "must": [],
                "filter": [
                  {
                    "bool": {
                      "should": [
                        {
                          "match": {
                            "src_ip": "8.8.8.8"
                          }
                        }
                      ],
                      "minimum_should_match": 1
                    }
                  },
                  {
                    "range": {
                      "ts": {
                        "format": "strict_date_optional_time",
                        "gte": "2024-08-08T07:14:29.534Z",
                        "lte": "2024-08-08T07:29:29.534Z"
                      }
                    }
                  }
                ],
                "should": [],
                "must_not": []
              }
            },
            "highlight": {
              "pre_tags": [
                "@kibana-highlighted-field@"
              ],
              "post_tags": [
                "@/kibana-highlighted-field@"
              ],
              "fields": {
                "*": {}
              },
              "fragment_size": 2147483647
            }
          },
          "track_total_hits": false,
          "preference": 1723081433520
        }
      },
      "options": {
        "sessionId": "198f200d-f1e2-4150-a6c2-f1ea13ff7d26",
        "isRestore": false,
        "strategy": "ese",
        "isStored": false,
        "executionContext": {
          "type": "application",
          "name": "discover",
          "description": "fetch documents",
          "url": "/app/discover",
          "id": ""
        }
      }
    },
    {
      "request": {
        "params": {
          "index": "xxxxxxxxx",
          "body": {
            "size": 0,
            "aggs": {
              "2": {
                "date_histogram": {
                  "field": "ts",
                  "fixed_interval": "30s",
                  "time_zone": "Asia/Shanghai",
                  "min_doc_count": 1
                }
              }
            },
            "script_fields": {},
            "stored_fields": [
              "*"
            ],
            "runtime_mappings": {},
            "query": {
              "bool": {
                "must": [],
                "filter": [
                  {
                    "bool": {
                      "should": [
                        {
                          "match": {
                            "src_ip": "8.8.8.8"
                          }
                        }
                      ],
                      "minimum_should_match": 1
                    }
                  },
                  {
                    "range": {
                      "ts": {
                        "format": "strict_date_optional_time",
                        "gte": "2024-08-08T07:14:29.534Z",
                        "lte": "2024-08-08T07:29:29.534Z"
                      }
                    }
                  }
                ],
                "should": [],
                "must_not": []
              }
            }
          },
          "track_total_hits": true,
          "preference": 1723081433520
        }
      },
      "options": {
        "sessionId": "198f200d-f1e2-4150-a6c2-f1ea13ff7d26",
        "isRestore": false,
        "strategy": "ese",
        "isStored": false,
        "executionContext": {
          "type": "application",
          "name": "discover",
          "description": "fetch chart data and total hits",
          "url": "/app/discover",
          "id": ""
        }
      }
    }
  ]
}
`
ckibana后台报错日志：
![B1746800-F27A-47CD-B926-BC35F7AD3481](https://github.com/user-attachments/assets/fb68cbc2-82a9-4072-9dd0-480528039cc0)

**Comment by linger000** [comment]
目前KQL语法还没做兼容。建议先试用Lucene语法。
