### ISSUE TITLE
无法创建index pattern

### ISSUE THREAD

**Issue by duaixy520** [TongchengOpenSource/ckibana#70]
clickhouse版本24.8.4.7，kibana和es版本6.8.2,添加了白名单，能够发现clickhouse表但是无法创建indexpattern
![304203e528282ba7db72cf4173ffdec](https://github.com/user-attachments/assets/8e0a9317-9199-402b-aff0-75b1576a8ef2)
![Uploading 3116252e5bd98e3456e40671d547c37.png…]()

**Comment by duaixy520** [comment]
已解决，想要以clickhouse表建立索引模式，不能输入通配符*,仅输入表名即可

**Comment by caojiaqiang** [comment]
创建indexpattern时，逻辑是输入的indexpattern需要跟表名完全匹配才会出来
