### ISSUE TITLE
quickstart 中 mock-filebeat 在非Root 用户下启动失败

### ISSUE THREAD

**Issue by white-cc** [TongchengOpenSource/ckibana#9]
当docker执行用户为root用户 和 文件 docker-compose/mock-filebeat.yml 用户不对应时，mock-filebeat 会启动失败。
`Exiting: error loading config file: config file ("filebeat.yml") must be owned by the user identifier (uid=1000) or root`
在quickstart 这种测试场景中，是不是考虑给ting001/file-beat-ck 加上  -strict.perms=false 启动参数
https://www.elastic.co/guide/en/beats/libbeat/5.3/config-file-permissions.html#_disabling_strict_permission_checks

**Comment by CodeRusher** [comment]
这个应该是权限问题
请问你在执行docker-compose用户是非root用户么？

**Comment by white-cc** [comment]
是的
应该是 ./config/mock-filebeat.yml 直接映射给了 /usr/share/filebeat/filebeat.yml
./config/mock-filebeat.yml 的 所有者 是 非root用户造成的。
chown 这个文件给 root用户可以解决

**Comment by CodeRusher** [comment]
好的，权限问题我们这边统一调整一下
你也可以直接提pr给我们
